
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Irvina
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nmptgs = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        resi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jkmotor = new javax.swing.JRadioButton();
        jkmobil = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tglmasuk = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        tglkeluar = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jmlhari = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Penitipan Motor dan Mobil \"RACHEL\"");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 20, 630, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Jalan Danau Laut Tawar G4H-15");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 70, 320, 22);

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 10, 1020, 90);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 110));

        tabel.setBackground(new java.awt.Color(153, 255, 204));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama Petugas", "No.Resi", "No.Polisi", "Jenis Kendaraan", "Tanggal Masuk", "Tanggal Keluar", "Jumlah Hari", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 670, 390));

        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 60, 30));

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(null);

        jLabel3.setText("Nama Petugas");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 10, 100, 30);
        jPanel2.add(nmptgs);
        nmptgs.setBounds(130, 10, 210, 40);

        jLabel4.setText("No. resi");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 70, 70, 30);

        resi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resiActionPerformed(evt);
            }
        });
        jPanel2.add(resi);
        resi.setBounds(130, 60, 210, 40);

        jLabel5.setText("No.Polisi");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 60, 30);
        jPanel2.add(nopol);
        nopol.setBounds(130, 110, 210, 40);

        jLabel6.setText("Jenis Kendaraan");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 170, 100, 30);

        buttonGroup1.add(jkmotor);
        jkmotor.setText("Motor");
        jPanel2.add(jkmotor);
        jkmotor.setBounds(130, 170, 100, 23);

        buttonGroup1.add(jkmobil);
        jkmobil.setText("Mobil");
        jkmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkmobilActionPerformed(evt);
            }
        });
        jPanel2.add(jkmobil);
        jkmobil.setBounds(240, 170, 90, 23);

        jLabel7.setText("Tanggal Masuk");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 220, 90, 30);
        jPanel2.add(tglmasuk);
        tglmasuk.setBounds(130, 210, 210, 40);

        jLabel8.setText("Tanggal Keluar");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 270, 90, 30);
        jPanel2.add(tglkeluar);
        tglkeluar.setBounds(130, 270, 210, 40);

        jLabel10.setText("Jumlah Hari");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 330, 90, 30);

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setText("Lihat Harga");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(20, 370, 320, 40);

        jmlhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlhariActionPerformed(evt);
            }
        });
        jPanel2.add(jmlhari);
        jmlhari.setBounds(130, 320, 210, 40);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel2.add(harga);
        harga.setBounds(130, 420, 210, 40);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 360, 480));

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setLayout(null);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(280, 20, 90, 30);

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);
        jButton2.setBounds(170, 20, 80, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(60, 20, 80, 30);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(400, 20, 80, 30);

        jButton4.setText("Print");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(510, 20, 80, 30);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(10, 10, 650, 60);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 670, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resiActionPerformed

    private void jkmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkmobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkmobilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String JK = "";
        if (jkmotor.isSelected()){
        }
        else
        {
            JK = "Motor";
        }
        if(jkmobil.isSelected())
            JK ="Mobil";
        
        if ("".equals(nmptgs.getText()) || "".equals(resi.getText()) || 
                "".equals(nopol.getText()) || "".equals(jmlhari.getText()) || "".equals(harga.getText()))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
    
    else
    {
        
        
        String SQL = "INSERT INTO tb_nitip (NamaPetugas,NoResi,NOPOL,JenisKendaraan,TanggalMasuk,TanggalKeluar,JumlahHari,Harga) "
                + "VALUES('"+nmptgs.getText()+"','"+resi.getText()+"', '"+nopol.getText()+"', '"+JK+"', '"+tglmasuk+"', '"+tglkeluar+"', '"+jmlhari.getText()+"', '"+harga.getText()+"' )";
        int status = KoneksiDB.execute(SQL);
        if (status == 1)
        {
            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nmptgs.setText("");
        resi.setText("");
        nopol.setText("");
        buttonGroup1.clearSelection();
        jmlhari.setText("");
        harga.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        int hitung = Integer.parseInt(jmlhari.getText());
        int jumlah = 0;
        jumlah = hitung*3000;
        harga.setText(String.valueOf(jumlah));
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int baris = tabel.getSelectedRow();
        
        if (baris != -1)
        {
            String id = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_nitip WHERE ='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
        
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu", "Error", JOptionPane.INFORMATION_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        selectData();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MessageFormat header = new MessageFormat("Penitipan Motor dan Mobil RACHEL");
        MessageFormat footer = new MessageFormat("Page {0,number,integer)");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
        System.err.format("Cannot Print %s%n", e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jmlhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlhariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmlhariActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jkmobil;
    private javax.swing.JRadioButton jkmotor;
    private javax.swing.JTextField jmlhari;
    private javax.swing.JTextField nmptgs;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField resi;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tglkeluar;
    private com.toedter.calendar.JDateChooser tglmasuk;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"id","NamaPetugas","NoResi","NOPOL","JenisKendaraan","TanggalMasuk","TanggalKeluar","JumlahHari","Harga"};
            DefaultTableModel dtm = new DefaultTableModel(null, kolom);
            String SQL = "SELECT * FROM tb_nitip";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            try{
                while(rs.next()) {
                    String id = rs.getString(1);
                    String NamaPetugas = rs.getString(2);
                    String NoResi = rs.getString(3);
                    String NOPOL= rs.getString(4);
                    String JenisKendaraan = "";
                    if ("Motor".equals(rs.getString(5))){
                        JenisKendaraan = "Motor";
                    }else {
                        JenisKendaraan = "Mobil";
                    }
                    String TanggalMasuk = rs.getString(6);
                    String TanggalKeluar = rs.getString(7);
                    String JumlahHari = rs.getString(8);
                    String Harga = rs.getString(9);
                    String data[] = {id,NamaPetugas,NoResi,NOPOL,JenisKendaraan,TanggalMasuk,TanggalKeluar,JumlahHari,Harga};
                    dtm.addRow(data);
                }
            } catch (SQLException ex){
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
           tabel.setModel(dtm);
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
